# Pull official base image
FROM python:3.10-alpine3.19

# Set work directory
WORKDIR /usr/src/app

# Set enviroment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Copy project
COPY . .

# Copy entrypoint script into the container
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

# Give execution permission to the entrypoint script
RUN chmod +x /usr/src/app/entrypoint.sh

# Set the entrypoint script as the entry point for the container
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]

# Run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
