# Generated by Django 5.0.4 on 2024-04-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido_paterno', models.CharField(default='', max_length=60)),
                ('apellido_materno', models.CharField(default='', max_length=60)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(default='', max_length=9)),
                ('fecha_dominio', models.DateField()),
                ('fecha_hosting', models.DateField()),
                ('link_pagina_web', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
