# Generated by Django 5.0.4 on 2024-04-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
