# Generated by Django 5.0.4 on 2024-04-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='link',
            field=models.CharField(default='', max_length=250),
        ),
    ]
