# Generated by Django 5.0.4 on 2024-05-08 19:24

import aplicaciones.proyectos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyectos_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='image',
            field=models.ImageField(default='', upload_to=aplicaciones.proyectos.models.upload_to),
        ),
    ]
